server:
  port: 7001

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db
#  mongodb:
#    embedded:
#      version: 3.6.5

logging:
  level:
    root: INFO


---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

  data:
    mongodb:
      host: mongodb