server:
  port: 7003

spring.datasource:
  url: jdbc:mysql://localhost/review-db
  username: user
  password: pwd
#    Following line is not required.
#    driverClassName: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

spring.datasource:
  url: jdbc:mysql://mysql/review-db
  driverClassName: com.mysql.cj.jdbc.Driver